name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'Makefile'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=theos_version_commit-sdks_version_commit >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-theos-sdk-version

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Build package
        run: |
          rm -f ${{ github.workspace }}/packages/*.deb
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Check if new Debs exist
        id: check-deb
        run: |
          if ls ${{ github.workspace }}/packages/*.deb 1> /dev/null 2>&1; then
            echo "has_deb=true" >> $GITHUB_OUTPUT
          else
            echo "has_deb=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check-deb.outputs.has_deb == 'true'
        id: release
        run: |
          LATEST_VERSION=$(gh release list --limit 1 --json tagName -q ".[0].tagName")
          if [ -z "$LATEST_VERSION" ]; then
            VERSION="1.0.0+1"
          else
            VERSION=$(echo "$LATEST_VERSION" | awk -F '+' '{printf "%s+%d", $1, $2+1}')
          fi
          gh release create $VERSION ${{ github.workspace }}/packages/*.deb \
            --title "DYYY $VERSION" \
            --notes "Automated release of .deb files"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload artifacts
        if: steps.check-deb.outputs.has_deb == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: DYYY
          path: ${{ github.workspace }}/packages/*.deb
